name: AlliedKingdoms
version: 0.4.0
main: dev.jkopecky.alliedkingdoms.AlliedKingdoms
description: A medieval take on factions.
api-version: '1.21.7'
author: Joseph Kopecky
website: https://jkopecky.dev
depend: [Vault]