name: AlliedKingdoms
version: 0.0.1
main: dev.jkopecky.alliedkingdoms.AlliedKingdoms
description: A medieval take on factions.
author: Joseph Kopecky
website: https://jkopecky.dev
api-version: '1.21.7'